sudo: required
services:
  - docker

before_install:
  - docker build -t daytalker/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true daytalker/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "daytalker"
  env: "Daytalker-env"
  bucket_name: "elasticbeanstalk-eu-north-1-205246707223"
  bucket_path: "daytalker"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"